# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/WorkSpace/HDL/uart_test/uart_test.srcs/sources_1/bd/uart_rx_design/ip/uart_rx_design_rst_ps7_0_50M_0/uart_rx_design_rst_ps7_0_50M_0.xci
# IP: The module: 'uart_rx_design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkSpace/HDL/uart_test/uart_test.srcs/sources_1/bd/uart_rx_design/ip/uart_rx_design_rst_ps7_0_50M_0/uart_rx_design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_rx_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/WorkSpace/HDL/uart_test/uart_test.srcs/sources_1/bd/uart_rx_design/ip/uart_rx_design_rst_ps7_0_50M_0/uart_rx_design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_rx_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/WorkSpace/HDL/uart_test/uart_test.srcs/sources_1/bd/uart_rx_design/ip/uart_rx_design_rst_ps7_0_50M_0/uart_rx_design_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_rx_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/WorkSpace/HDL/uart_test/uart_test.srcs/sources_1/bd/uart_rx_design/ip/uart_rx_design_rst_ps7_0_50M_0/uart_rx_design_rst_ps7_0_50M_0.xci
# IP: The module: 'uart_rx_design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkSpace/HDL/uart_test/uart_test.srcs/sources_1/bd/uart_rx_design/ip/uart_rx_design_rst_ps7_0_50M_0/uart_rx_design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_rx_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/WorkSpace/HDL/uart_test/uart_test.srcs/sources_1/bd/uart_rx_design/ip/uart_rx_design_rst_ps7_0_50M_0/uart_rx_design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_rx_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/WorkSpace/HDL/uart_test/uart_test.srcs/sources_1/bd/uart_rx_design/ip/uart_rx_design_rst_ps7_0_50M_0/uart_rx_design_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_rx_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
