# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constr/zybo_z7_10_master.xdc

# Block Designs: bd/apuf_parallel_uart_design/apuf_parallel_uart_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==apuf_parallel_uart_design || ORIG_REF_NAME==apuf_parallel_uart_design} -quiet] -quiet

# IP: bd/apuf_parallel_uart_design/ip/apuf_parallel_uart_design_processing_system7_0_0/apuf_parallel_uart_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==apuf_parallel_uart_design_processing_system7_0_0 || ORIG_REF_NAME==apuf_parallel_uart_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/apuf_parallel_uart_design/ip/apuf_parallel_uart_design_axi_uartlite_0_0/apuf_parallel_uart_design_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==apuf_parallel_uart_design_axi_uartlite_0_0 || ORIG_REF_NAME==apuf_parallel_uart_design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/apuf_parallel_uart_design/ip/apuf_parallel_uart_design_uart_rx_0_0/apuf_parallel_uart_design_uart_rx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==apuf_parallel_uart_design_uart_rx_0_0 || ORIG_REF_NAME==apuf_parallel_uart_design_uart_rx_0_0} -quiet] -quiet

# IP: bd/apuf_parallel_uart_design/ip/apuf_parallel_uart_design_uart_tx_0_0/apuf_parallel_uart_design_uart_tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==apuf_parallel_uart_design_uart_tx_0_0 || ORIG_REF_NAME==apuf_parallel_uart_design_uart_tx_0_0} -quiet] -quiet

# IP: bd/apuf_parallel_uart_design/ip/apuf_parallel_uart_design_apuf_parallel_0_0/apuf_parallel_uart_design_apuf_parallel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==apuf_parallel_uart_design_apuf_parallel_0_0 || ORIG_REF_NAME==apuf_parallel_uart_design_apuf_parallel_0_0} -quiet] -quiet

# IP: bd/apuf_parallel_uart_design/ip/apuf_parallel_uart_design_ps7_0_axi_periph_0/apuf_parallel_uart_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==apuf_parallel_uart_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==apuf_parallel_uart_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/apuf_parallel_uart_design/ip/apuf_parallel_uart_design_rst_ps7_0_50M_0/apuf_parallel_uart_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==apuf_parallel_uart_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==apuf_parallel_uart_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/apuf_parallel_uart_design/ip/apuf_parallel_uart_design_auto_pc_0/apuf_parallel_uart_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==apuf_parallel_uart_design_auto_pc_0 || ORIG_REF_NAME==apuf_parallel_uart_design_auto_pc_0} -quiet] -quiet

# XDC: bd/apuf_parallel_uart_design/apuf_parallel_uart_design_ooc.xdc
