# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/WorkSpace/HDL/uart_test/uart_test.srcs/constrs_2/new/constr.xdc

# Block Designs: bd/uart_tx_design/uart_tx_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_tx_design || ORIG_REF_NAME==uart_tx_design} -quiet] -quiet

# IP: bd/uart_tx_design/ip/uart_tx_design_processing_system7_0_0/uart_tx_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_tx_design_processing_system7_0_0 || ORIG_REF_NAME==uart_tx_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/uart_tx_design/ip/uart_tx_design_UART_TX_0_0/uart_tx_design_UART_TX_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_tx_design_UART_TX_0_0 || ORIG_REF_NAME==uart_tx_design_UART_TX_0_0} -quiet] -quiet

# IP: bd/uart_tx_design/ip/uart_tx_design_test_in_0_0/uart_tx_design_test_in_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_tx_design_test_in_0_0 || ORIG_REF_NAME==uart_tx_design_test_in_0_0} -quiet] -quiet

# IP: bd/uart_tx_design/ip/uart_tx_design_axi_uartlite_0_0/uart_tx_design_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_tx_design_axi_uartlite_0_0 || ORIG_REF_NAME==uart_tx_design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/uart_tx_design/ip/uart_tx_design_ps7_0_axi_periph_0/uart_tx_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_tx_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==uart_tx_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/uart_tx_design/ip/uart_tx_design_rst_ps7_0_50M_0/uart_tx_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_tx_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==uart_tx_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/uart_tx_design/ip/uart_tx_design_UART_RX_0_0/uart_tx_design_UART_RX_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_tx_design_UART_RX_0_0 || ORIG_REF_NAME==uart_tx_design_UART_RX_0_0} -quiet] -quiet

# IP: bd/uart_tx_design/ip/uart_tx_design_auto_pc_0/uart_tx_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_tx_design_auto_pc_0 || ORIG_REF_NAME==uart_tx_design_auto_pc_0} -quiet] -quiet

# XDC: bd/uart_tx_design/uart_tx_design_ooc.xdc
