# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/WorkSpace/HDL/yadro_practice/project/apuf_test/apuf_test.cache/wt [current_project]
set_property parent.project_path D:/WorkSpace/HDL/yadro_practice/project/apuf_test/apuf_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.1 [current_project]
set_property ip_output_repo d:/WorkSpace/HDL/yadro_practice/project/apuf_test/apuf_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog D:/WorkSpace/HDL/yadro_practice/inc/general_config.vh
read_mem D:/WorkSpace/HDL/yadro_practice/project/apuf_test/apuf_test.srcs/sources_1/new/temp.mem
read_verilog -sv D:/WorkSpace/HDL/yadro_practice/pkg/general_param_pkg.sv
read_verilog -library xil_defaultlib -sv {
  D:/WorkSpace/HDL/yadro_practice/pkg/uart_param_pkg.sv
  D:/WorkSpace/HDL/yadro_practice/pkg/apuf_param_pkg.sv
  D:/WorkSpace/HDL/yadro_practice/src/lfsr.sv
  D:/WorkSpace/HDL/yadro_practice/src/d_ff.sv
  D:/WorkSpace/HDL/yadro_practice/src/apuf_path.sv
  D:/WorkSpace/HDL/yadro_practice/src/sipo.sv
  D:/WorkSpace/HDL/yadro_practice/src/uart_rx.sv
  D:/WorkSpace/HDL/yadro_practice/src/apuf.sv
  D:/WorkSpace/HDL/yadro_practice/src/mux2x1.sv
  D:/WorkSpace/HDL/yadro_practice/src/uart_tx.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/WorkSpace/HDL/yadro_practice/project/apuf_test/apuf_test.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files D:/WorkSpace/HDL/yadro_practice/project/apuf_test/apuf_test.srcs/constrs_1/new/constr.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top apuf -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef apuf.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file apuf_utilization_synth.rpt -pb apuf_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
