# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/WorkSpace/HDL/uart_test/uart_test.srcs/constrs_1/new/constr.xdc

# Block Designs: bd/uart_rx_design/uart_rx_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_rx_design || ORIG_REF_NAME==uart_rx_design} -quiet] -quiet

# IP: bd/uart_rx_design/ip/uart_rx_design_processing_system7_0_0/uart_rx_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_rx_design_processing_system7_0_0 || ORIG_REF_NAME==uart_rx_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/uart_rx_design/ip/uart_rx_design_UART_RX_0_0/uart_rx_design_UART_RX_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_rx_design_UART_RX_0_0 || ORIG_REF_NAME==uart_rx_design_UART_RX_0_0} -quiet] -quiet

# IP: bd/uart_rx_design/ip/uart_rx_design_test_out_0_0/uart_rx_design_test_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_rx_design_test_out_0_0 || ORIG_REF_NAME==uart_rx_design_test_out_0_0} -quiet] -quiet

# IP: bd/uart_rx_design/ip/uart_rx_design_axi_uartlite_0_0/uart_rx_design_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_rx_design_axi_uartlite_0_0 || ORIG_REF_NAME==uart_rx_design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/uart_rx_design/ip/uart_rx_design_ps7_0_axi_periph_0/uart_rx_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_rx_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==uart_rx_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/uart_rx_design/ip/uart_rx_design_rst_ps7_0_50M_0/uart_rx_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_rx_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==uart_rx_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/uart_rx_design/ip/uart_rx_design_auto_pc_0/uart_rx_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_rx_design_auto_pc_0 || ORIG_REF_NAME==uart_rx_design_auto_pc_0} -quiet] -quiet

# XDC: bd/uart_rx_design/uart_rx_design_ooc.xdc
