# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/WorkSpace/HDL/uart_test/uart_test.srcs/sources_1/bd/uart_tx_design/ip/uart_tx_design_processing_system7_0_0/uart_tx_design_processing_system7_0_0.xci
# IP: The module: 'uart_tx_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkSpace/HDL/uart_test/uart_test.srcs/sources_1/bd/uart_tx_design/ip/uart_tx_design_processing_system7_0_0/uart_tx_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_tx_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/WorkSpace/HDL/uart_test/uart_test.srcs/sources_1/bd/uart_tx_design/ip/uart_tx_design_processing_system7_0_0/uart_tx_design_processing_system7_0_0.xci
# IP: The module: 'uart_tx_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkSpace/HDL/uart_test/uart_test.srcs/sources_1/bd/uart_tx_design/ip/uart_tx_design_processing_system7_0_0/uart_tx_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_tx_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
