# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/WorkSpace/HDL/yadro_practice/project/apuf_parallel_uart_v1.0/apuf_parallel_uart_v1.0.srcs/sources_1/bd/apuf_parallel_uart_design/ip/apuf_parallel_uart_design_processing_system7_0_0/apuf_parallel_uart_design_processing_system7_0_0.xci
# IP: The module: 'apuf_parallel_uart_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkSpace/HDL/yadro_practice/project/apuf_parallel_uart_v1.0/apuf_parallel_uart_v1.0.srcs/sources_1/bd/apuf_parallel_uart_design/ip/apuf_parallel_uart_design_processing_system7_0_0/apuf_parallel_uart_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'apuf_parallel_uart_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/WorkSpace/HDL/yadro_practice/project/apuf_parallel_uart_v1.0/apuf_parallel_uart_v1.0.srcs/sources_1/bd/apuf_parallel_uart_design/ip/apuf_parallel_uart_design_processing_system7_0_0/apuf_parallel_uart_design_processing_system7_0_0.xci
# IP: The module: 'apuf_parallel_uart_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkSpace/HDL/yadro_practice/project/apuf_parallel_uart_v1.0/apuf_parallel_uart_v1.0.srcs/sources_1/bd/apuf_parallel_uart_design/ip/apuf_parallel_uart_design_processing_system7_0_0/apuf_parallel_uart_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'apuf_parallel_uart_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
